"""Guard: the committed landing pages must match what the generator produces.

``public/<slug>.html`` and ``public/sitemap.xml`` are generated by
``scripts/build_landing_pages.py``. Hand-editing the HTML is the failure mode
this guards against — the edit silently disappears the next time anyone runs
the generator, and in the meantime the page and its source of truth disagree.

Same contract as ``tests/test_web_assets.py``: if these fail, re-run the
generator and commit the result rather than editing the output.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
PUBLIC = ROOT / "public"
REBUILD = "run `python scripts/build_landing_pages.py` and commit the result"


def _load_builder():
    spec = importlib.util.spec_from_file_location(
        "build_landing_pages", ROOT / "scripts" / "build_landing_pages.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


BUILDER = _load_builder()


@pytest.mark.parametrize("page", BUILDER.PAGES, ids=lambda p: p["slug"])
def test_landing_page_matches_generator(page):
    path = PUBLIC / f"{page['slug']}.html"
    assert path.exists(), f"{path.name} is missing — {REBUILD}"
    assert path.read_text() == BUILDER.render(page), f"{path.name} is stale — {REBUILD}"


def test_sitemap_matches_generator():
    path = PUBLIC / "sitemap.xml"
    assert path.read_text() == BUILDER.render_sitemap(), f"sitemap.xml is stale — {REBUILD}"


@pytest.mark.parametrize("page", BUILDER.PAGES, ids=lambda p: p["slug"])
def test_premium_pages_disclose_the_paywall(page):
    """A landing page for a gated model must say so, above the fold.

    RDCF and HDEBT need Analyst Pro (see PREMIUM_MODELS in assets/terminal.js
    and the server-side gate in api/premium.py). A page that advertises them
    as a free calculator sends search traffic into a paywall it wasn't warned
    about, which is both a bad experience and a false claim.
    """
    html = (PUBLIC / f"{page['slug']}.html").read_text()
    if page["plan"] == "pro":
        assert "Analyst Pro" in html, f"{page['slug']} must disclose that it is gated"
        assert 'class="plan-note"' in html
        # ...and must not simultaneously claim to be free.
        assert "Runs free in your browser" not in html
    else:
        assert 'class="plan-note"' not in html


@pytest.mark.parametrize("page", BUILDER.PAGES, ids=lambda p: p["slug"])
def test_schema_offer_price_matches_the_real_plan(page):
    """Structured-data price must be the real one, not aspirational.

    Stale or invented price markup is its own manual-action risk with Google,
    so this pins the JSON-LD offer to the actual entitlement.
    """
    offer = BUILDER._app_schema(page)["offers"]
    assert offer["priceCurrency"] == "USD"
    assert offer["price"] == ("0" if page["plan"] == "free" else "29")
